# Generated by Django 2.2.7 on 2020-01-14 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_address', models.CharField(max_length=50)),
                ('Total_price', models.IntegerField(default=0)),
                ('Order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_img', models.ImageField(blank=True, null=True, upload_to='bread_img/')),
                ('P_name', models.CharField(max_length=50)),
                ('P_price', models.IntegerField(default=0)),
                ('P_nutrition', models.TextField(blank=True, null=True)),
                ('P_info', models.TextField(blank=True, null=True)),
                ('P_sales', models.IntegerField(default=0)),
                ('P_newProduct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_phone', models.CharField(max_length=11)),
                ('U_is_active', models.BooleanField(default=False)),
                ('U_grade', models.IntegerField(default=2)),
                ('U_groupName', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_count', models.IntegerField(default=0)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boeun_bread.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boeun_bread.Profile'),
        ),
        migrations.CreateModel(
            name='Cart_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_count', models.IntegerField(default=0)),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boeun_bread.Cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boeun_bread.Profile'),
        ),
    ]
