# Generated by Django 2.2.7 on 2020-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfile',
            name='file',
            field=models.FileField(upload_to='board/'),
        ),
    ]
