# Generated by Django 2.2.7 on 2020-03-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('1', '배송불만(지연,반품)'), ('2', '홈페이지 사용 불편'), ('3', '제품(빵) 가격 불만'), ('4', '제품(빵) 품질 불만'), ('5', '기타')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boeun_bread.Profile')),
            ],
        ),
    ]
