# Generated by Django 2.2.7 on 2020-01-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_newProduct',
            field=models.BooleanField(default=False),
        ),
    ]
