# Generated by Django 2.2 on 2020-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='question_status',
            field=models.BooleanField(default=False),
        ),
    ]
