# Generated by Django 2.2.7 on 2020-03-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0002_qna_question_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=30)),
                ('delivery_company', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(choices=[('1', '상품준비중'), ('2', '배송중'), ('3', '배송완료')], max_length=1)),
            ],
        ),
    ]
