# Generated by Django 2.2.7 on 2020-03-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0002_reason'),
        ('boeun_bread', '0002_qna_is_private'),
    ]

    operations = [
    ]
