# Generated by Django 2.2.7 on 2020-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0004_auto_20200310_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_receipt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, default='결제대기', max_length=200, null=True),
        ),
    ]
