# Generated by Django 2.2.7 on 2020-03-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0004_auto_20200310_1632'),
        ('boeun_bread', '0005_auto_20200310_1808'),
    ]

    operations = [
    ]
