# Generated by Django 2.2.7 on 2020-03-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0007_auto_20200311_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boeun_bread.Order'),
        ),
    ]
