# Generated by Django 2.2.7 on 2020-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0008_auto_20200311_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='non_user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='non_user_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
