# Generated by Django 2.2.7 on 2020-03-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0009_auto_20200311_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='non_user_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='non_user_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='non_user_phone',
        ),
    ]
