# Generated by Django 2.2.7 on 2020-03-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boeun_bread', '0010_auto_20200312_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='non_user_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='non_user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='non_user_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
